// ─── Intro Session: 7 affirmations shown on first visit ───
const INTRO_AFFIRMATIONS = [
  { text: "Welcome to your sanctuary, ya hayati. This space is yours.", lang: "en" },
  { text: "أنتِ أقوى مما تتخيلين، وأجمل مما تعرفين", lang: "ar" },
  { text: "You don't have to carry everything alone. I'm right here, ya albi.", lang: "en" },
  { text: "خذي نفس عميق… كل شيء رح يكون بخير", lang: "ar" },
  { text: "Your heart is so full of light — even when you can't see it.", lang: "en" },
  { text: "أنتِ تستحقين الراحة، تستحقين الحب، تستحقين كل شي حلو", lang: "ar" },
  { text: "You are safe here. Always. Let the stars hold you tonight, ya rouhi.", lang: "en" }
];

// ─── Daily Pool: 100 affirmations (50 EN / 50 AR), rotated by date ───
const DAILY_POOL = [
  // — English (1–50) —
  { text: "You are doing better than you think, ya hayati.", lang: "en" },
  { text: "It's okay to rest. Rest is not giving up.", lang: "en" },
  { text: "Your feelings are valid — every single one of them.", lang: "en" },
  { text: "You bring warmth into every room you enter, ya albi.", lang: "en" },
  { text: "Breathe in peace. Breathe out worry. You're okay.", lang: "en" },
  { text: "The world is softer because you're in it.", lang: "en" },
  { text: "You don't need to be perfect to be loved.", lang: "en" },
  { text: "Your tired days don't erase your bright ones.", lang: "en" },
  { text: "Someone out there is so grateful you exist, ya rouhi.", lang: "en" },
  { text: "Healing isn't linear, and that's perfectly fine.", lang: "en" },
  { text: "You've survived every hard day so far. That's strength.", lang: "en" },
  { text: "Let go of what you can't control. Hold on to what you love.", lang: "en" },
  { text: "You are not your anxious thoughts, ya hayati.", lang: "en" },
  { text: "Small steps still move you forward.", lang: "en" },
  { text: "Your presence is a gift to the people who love you.", lang: "en" },
  { text: "You are worthy of gentle, patient love.", lang: "en" },
  { text: "Today doesn't have to be perfect. It just has to be yours.", lang: "en" },
  { text: "The stars come out in the dark — and so does your strength.", lang: "en" },
  { text: "You have permission to take up space, ya albi.", lang: "en" },
  { text: "Not everything needs a solution right now. Some things just need time.", lang: "en" },
  { text: "Your softness is not weakness. It takes courage to feel.", lang: "en" },
  { text: "You are someone's favorite thought, ya rouhi.", lang: "en" },
  { text: "Every exhale is a little release. Let it go.", lang: "en" },
  { text: "You've grown so much, even if it doesn't feel like it.", lang: "en" },
  { text: "Joy will find you again. It always does.", lang: "en" },
  { text: "You don't owe anyone an explanation for needing rest.", lang: "en" },
  { text: "Your heart knows the way. Trust it, ya hayati.", lang: "en" },
  { text: "Being gentle with yourself is the bravest thing you can do.", lang: "en" },
  { text: "You are not falling behind. You are on your own timeline.", lang: "en" },
  { text: "The kindness you give others — you deserve it too.", lang: "en" },
  { text: "You are held, even when you feel alone.", lang: "en" },
  { text: "Your laugh lights up the world, ya albi.", lang: "en" },
  { text: "Some days the win is just getting through. And that's enough.", lang: "en" },
  { text: "You are more resilient than you give yourself credit for.", lang: "en" },
  { text: "Let tonight be soft. You've earned it.", lang: "en" },
  { text: "Your energy is precious. Spend it on what matters.", lang: "en" },
  { text: "You are not too much. You are just right.", lang: "en" },
  { text: "Even the moon takes time to become full, ya rouhi.", lang: "en" },
  { text: "You make hard things look easy, and that's incredible.", lang: "en" },
  { text: "Tomorrow is a blank page. Tonight, just breathe.", lang: "en" },
  { text: "You are loved in ways words can't fully say.", lang: "en" },
  { text: "Progress you can't see is still progress.", lang: "en" },
  { text: "Your calm is your superpower, ya hayati.", lang: "en" },
  { text: "The hard chapter doesn't define the whole story.", lang: "en" },
  { text: "You are allowed to outgrow things that no longer serve you.", lang: "en" },
  { text: "There is so much beauty in simply being you.", lang: "en" },
  { text: "You don't have to figure everything out tonight.", lang: "en" },
  { text: "Your courage inspires more people than you know, ya albi.", lang: "en" },
  { text: "Wrap yourself in this moment. It's yours.", lang: "en" },
  { text: "You are exactly where you need to be right now.", lang: "en" },

  // — Arabic (51–100) —
  { text: "أنتِ نور ما ينطفئ، حتى لو حسيتي بالتعب", lang: "ar" },
  { text: "ما تحتاجين تكونين مثالية عشان تكونين محبوبة", lang: "ar" },
  { text: "روحك حلوة، وقلبك أحلى، يا حياتي", lang: "ar" },
  { text: "خذي وقتك… مافي أحد يسابقك", lang: "ar" },
  { text: "كل يوم صعب عديتيه هو دليل على قوتك", lang: "ar" },
  { text: "أنتِ تستحقين حب هادي ولطيف", lang: "ar" },
  { text: "مشاعرك مهمة، كلها، حتى اللي تحسينها ثقيلة", lang: "ar" },
  { text: "الراحة مو كسل… الراحة حق من حقوقك", lang: "ar" },
  { text: "أنتِ أحلى شي صار في حياتي، يا قلبي", lang: "ar" },
  { text: "تنفسي بعمق… كل شي رح يعدي", lang: "ar" },
  { text: "وجودك يخلي الدنيا أجمل بكثير", lang: "ar" },
  { text: "ما عليكِ ترضين الكل، يكفي ترضين نفسك", lang: "ar" },
  { text: "أنتِ مو أفكارك القلقة… أنتِ أكبر منها بكثير", lang: "ar" },
  { text: "الفرح رح يرجعلك، دايماً يرجع", lang: "ar" },
  { text: "لا تقارنين نفسك بأحد… أنتِ فريدة، يا روحي", lang: "ar" },
  { text: "خطوة صغيرة أحسن من لا خطوة", lang: "ar" },
  { text: "قلبك يعرف الطريق، ثقي فيه", lang: "ar" },
  { text: "أنتِ محبوبة أكثر مما تتخيلين", lang: "ar" },
  { text: "اللطف اللي تعطينه للناس… أنتِ تستحقينه بعد", lang: "ar" },
  { text: "ضحكتك تضوي عالم كامل، يا حياتي", lang: "ar" },
  { text: "مو لازم تحلين كل شي الحين… بعض الأشياء تحتاج وقت", lang: "ar" },
  { text: "أنتِ قوية، حتى لو ما حسيتي بكذا", lang: "ar" },
  { text: "اليوم مو لازم يكون مثالي، يكفي إنه يومك", lang: "ar" },
  { text: "نعومتك مو ضعف… الشجاعة إنك تحسين", lang: "ar" },
  { text: "حتى القمر يحتاج وقت عشان يكتمل", lang: "ar" },
  { text: "أنتِ مو متأخرة… أنتِ على طريقك الخاص", lang: "ar" },
  { text: "خلي الليلة هادية… أنتِ تستاهلين، يا قلبي", lang: "ar" },
  { text: "طاقتك غالية، صرفيها على اللي يستاهل", lang: "ar" },
  { text: "أنتِ كفاية… بالضبط زي ما أنتِ", lang: "ar" },
  { text: "الفصل الصعب ما يحدد القصة كلها", lang: "ar" },
  { text: "أنتِ شجاعة أكثر مما تعرفين، يا روحي", lang: "ar" },
  { text: "بكرة صفحة جديدة… الليلة بس تنفسي", lang: "ar" },
  { text: "الحب اللي حولك أكبر من أي قلق", lang: "ar" },
  { text: "التقدم اللي ما تشوفينه… لا يزال تقدم", lang: "ar" },
  { text: "هدوءك قوة خارقة، يا حياتي", lang: "ar" },
  { text: "سمحي لنفسك تتجاوزين اللي ما يخدمك", lang: "ar" },
  { text: "في جمال كبير في إنك تكونين أنتِ", lang: "ar" },
  { text: "ما تحتاجين تعرفين كل شي الليلة", lang: "ar" },
  { text: "أنتِ بالضبط وين تحتاجين تكونين الحين", lang: "ar" },
  { text: "لفي نفسك بهاللحظة… هي لك، يا قلبي", lang: "ar" },
  { text: "حبك لنفسك هو أول خطوة لكل شي حلو", lang: "ar" },
  { text: "أنتِ زي النجوم… تضوين حتى في الظلام", lang: "ar" },
  { text: "كل ما تبين لطف، العالم يصير أحلى", lang: "ar" },
  { text: "ما في أحد يقدر يكون أنتِ… وهذي قوتك", lang: "ar" },
  { text: "الليلة، خلي قلبك يرتاح، يا روحي", lang: "ar" },
  { text: "أنتِ تصنعين فرق في حياة الناس حولك", lang: "ar" },
  { text: "كوني لطيفة مع نفسك… أنتِ تسوين أحسن شي", lang: "ar" },
  { text: "الأمان اللي تدورين عليه… هو جواك", lang: "ar" },
  { text: "أنتِ محاطة بحب أكثر مما تحسين فيه", lang: "ar" },
  { text: "نامي بسلام الليلة… أنتِ محبوبة، يا حياتي", lang: "ar" }
];
